# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/peter/Documents/GitHub/EGRE-365-Final-Project/EGRE-365-Final-Project/EGRE-365-Final-Project.cache/wt [current_project]
set_property parent.project_path C:/Users/peter/Documents/GitHub/EGRE-365-Final-Project/EGRE-365-Final-Project/EGRE-365-Final-Project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/peter/Documents/GitHub/EGRE-365-Final-Project/EGRE-365-Final-Project/EGRE-365-Final-Project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/peter/Documents/GitHub/EGRE-365-Final-Project/1_clk_delay_register.vhd
  C:/Users/peter/Documents/GitHub/EGRE-365-Final-Project/ADC_Controller_fsm.vhd
  C:/Users/peter/Documents/GitHub/EGRE-365-Final-Project/TWICtl.vhd
  C:/Users/peter/Documents/GitHub/EGRE-365-Final-Project/start_trigger.vhd
  C:/Users/peter/Documents/GitHub/EGRE-365-Final-Project/ADC_toplevel_skeleton.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/peter/Documents/GitHub/EGRE-365-Final-Project/Nexys4DDR_Master_skeleton.xdc
set_property used_in_implementation false [get_files C:/Users/peter/Documents/GitHub/EGRE-365-Final-Project/Nexys4DDR_Master_skeleton.xdc]


synth_design -top ADC_toplevel -part xc7a100tcsg324-1


write_checkpoint -force -noxdef ADC_toplevel.dcp

catch { report_utilization -file ADC_toplevel_utilization_synth.rpt -pb ADC_toplevel_utilization_synth.pb }
